// License Template Utilities
export function generateLicenseTXT({ beatTitle, buyerName, licenseType, date, artistName = "AgonyBeats", price = "XX.XX" }) {
    const config = getLicenseConfig(licenseType);

    const lines = [
        "LICENSE AGREEMENT",
        "",
        `THIS AGREEMENT made as of ${date} (the "Effective Date") by and between:`,
        "",
        `Licensor: ${artistName} ("Producer")`,
        `Licensee: ${buyerName} ("Artist")`,
        "",
        `WHEREAS, Producer is the owner of the copyright in the musical composition and sound recording entitled "${beatTitle}" (the "Beat"); and`,
        "",
        `WHEREAS, Artist wishes to purchase a license to use the Beat for the creation of a new musical work (the "New Song");`,
        "",
        "NOW, THEREFORE, subject to the terms and conditions contained herein, the parties agree as follows:",
        "",
        "1. GRANT OF RIGHTS",
        `Producer hereby grants to Artist a ${config.exclusivity} License to use the Beat in the creation of the New Song.`,
        "This license allows Artist to:",
        "   - Record vocals/lyrics over the Beat.",
        `   - Distribute the New Song for ${config.profit}.`,
        "   - Perform the New Song publicly.",
        `   - ${config.streams} Audio Streams.`,
        `   - ${config.videos} Music Video(s).`,
        `   - ${config.radio}.`,
        "",
        "2. PAYMENT",
        "Artist has paid the license fee for the rights granted herein. This is a non-refundable payment.",
        "",
        "3. ROYALTIES & PUBLISHING",
        "   - Producer retains 100% ownership of the underlying Beat composition.",
        "   - Artist owns 100% of their lyrics and vocal melody.",
        "   - Publishing Split: 50% to Producer (Writer/Composer) / 50% to Artist (Lyrics).",
        "   - Artist shall register the New Song with their PRO (ASCAP/BMI/etc.) listing AgonyBeats as a songwriter.",
        "",
        "4. CREDIT",
        "In all projects where the Beat is used, Artist shall give credit to Producer in substantially the following format:",
        '"Prod. by AgonyBeats"',
        "",
        "5. DELIVERY",
        `Producer agrees to deliver the Beat in the following format(s): ${config.files}.`,
        "",
        "6. RESTRICTIONS",
        "   - Artist may NOT resell, sub-license, or redistribute the Beat in its original form.",
        '   - Artist may NOT use the Beat for "Content ID" or copyright registration systems (e.g., TuneCore, DistroKid) that would trigger false copyright claims against other license holders.',
        "",
        "7. TERM",
        "This Agreement shall remain in full force and effect so long as Artist complies with the usage limits described in Section 1. If Artist exceeds these limits (e.g., more streams than allowed), a new license must be purchased.",
        "",
        "8. INDEMNIFICATION",
        "Artist agrees to indemnify and hold Producer harmless from any claims resulting from Artist's use of the Beat (e.g., uncleared samples in lyrics, defamation).",
        "",
        "9. GOVERNING LAW",
        "This Agreement shall be governed by the laws of Italy/International Copyright Law.",
        "",
        "----------------------------------------------------------------------",
        "ACCEPTED AND AGREED:",
        "",
        `LICENSOR: ${artistName}`,
        `LICENSEE: ${buyerName}`,
        `DATE: ${date}`,
        "----------------------------------------------------------------------",
        "GENERATED BY AGONYBEATS STORE"
    ];

    return lines.join("\n");
}

function getLicenseConfig(type) {
    const t = type.toLowerCase();

    if (t.includes('non-profit') || t.includes('free')) {
        return {
            exclusivity: "Non-Exclusive / Non-Profit",
            profit: "Non-Profit Use Only (No Monetization)",
            streams: "2,000",
            videos: "0",
            radio: "No Radio Rights",
            files: "MP3"
        };
    }

    if (t.includes('basic') || t.includes('lease')) {
        return {
            exclusivity: "Non-Exclusive",
            profit: "For-Profit Use",
            streams: "50,000",
            videos: "1",
            radio: "No Radio Rights",
            files: "MP3"
        };
    }

    if (t.includes('premium') || t.includes('trackout')) {
        return {
            exclusivity: "Non-Exclusive",
            profit: "For-Profit Use",
            streams: "500,000",
            videos: "Unlimited",
            radio: "2 Radio Stations",
            files: "WAV + MP3"
        };
    }

    if (t.includes('exclusive') || t.includes('unlimited')) {
        return {
            exclusivity: "Exclusive (or Unlimited Rights)",
            profit: "Unlimited For-Profit Use",
            streams: "Unlimited",
            videos: "Unlimited",
            radio: "Unlimited Radio Rights",
            files: "WAV + MP3 + Stems"
        };
    }

    if (t.includes('test')) {
        return {
            exclusivity: "Non-Exclusive (Test)",
            profit: "Testing Purposes Only",
            streams: "0",
            videos: "0",
            radio: "No",
            files: "MP3 (Test File)"
        };
    }

    // Fallback
    return {
        exclusivity: "Non-Exclusive",
        profit: "Standard Use",
        streams: "Standard",
        videos: "1",
        radio: "No",
        files: "MP3"
    };
}
